DM-46471: cm-service cli update collections and update child config need to be explicitly passed
lsst-dm/cm-service pull request #103
Opened 2024-09-24 20:21 UTC by eigerx

2024-09-24 20:46 UTC, fritzm approved these changes
LGTM -- thanks!

2024-09-25 17:56 UTC, eacharles requested changes

2024-09-25 17:56 UTC, eacharles commented on examples/start_hsc_micro.yaml
it looks like a number of changes from your working version snuck into the PR in the start_hsc_micro.yaml file.   You probably want to back everything except the collection -> collections fix out.

2024-09-25 17:56 UTC, eacharles commented on src/lsst/cmservice/db/node.py
> +        for key, value in resolved_collections:
this probably needs to be `for key, value in resolved_collections.itemsI()`

2024-09-25 18:28 UTC, eacharles commented
You are also going to want to update tests/db/test_micro.py to 

1. Grab the campaign like so: campaign = await interface.load_and_create_campaign(...)
2. override the MUST_OVERRIDE stuff in the campaign.collections with  await campaign.update_collections(...)
3. overide the MUST_OVERRIDE stuff in the campaign.data with  await campaign.update_data_dict(...).   I'd recommend setting prod_area to something different that output/archive...  maybe output_test/archive
4. clean the prod_area with os.system('\rm -rf output_test/archive') at the end of the test.

2024-09-26 21:42 UTC, eacharles commented on examples/start_hsc_micro.yaml
> +        lsst_version: w_2024_38
Please change this to MUST_OVERRIDE

2024-09-26 21:44 UTC, eacharles commented on examples/start_hsc_micro.yaml
> +        butler_repo: '/repo/main'
I think it would be better to leave these commented.

2024-09-26 21:44 UTC, eacharles approved these changes
Looks good expect for a couple of things still outstanding in start_hsc_micro.yaml

2024-09-26 21:58 UTC, merged